# Generated by Django 3.0.5 on 2020-04-13 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Drink_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=255)),
                ('d_desc', models.CharField(default='', max_length=255)),
                ('cost', models.IntegerField()),
                ('drink_type', models.CharField(choices=[('Coffee', 'Coffee'), ('Juice', 'Juice')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruit_name', models.CharField(max_length=30)),
                ('fruit_desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('Local_buy', 'Local buy'), ('Online_buy', 'Online buy')], max_length=255)),
                ('Order_payment', models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit')], max_length=255)),
                ('date', models.DateTimeField(auto_now=True)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_date', models.DateField(auto_now=True)),
                ('e_date', models.DateField(auto_now=True)),
                ('promo_desc', models.TextField()),
                ('promo_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Queue_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reciept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField()),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_type', models.CharField(choices=[('Coffee', 'Coffee'), ('Juice', 'Juice')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Coffee_and_other',
            fields=[
                ('specials', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='product.Special')),
                ('coffee_type', models.CharField(choices=[('Hot', 'Hot'), ('Iced', 'Iced'), ('Frappe', 'Frappe')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Juice',
            fields=[
                ('special_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='product.Special')),
            ],
        ),
        migrations.CreateModel(
            name='Order_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('d_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Drink_info')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Order')),
                ('special_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Special')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='promo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Promotion'),
        ),
        migrations.AddField(
            model_name='order',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Queue_info'),
        ),
        migrations.AddField(
            model_name='order',
            name='receipt_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Reciept'),
        ),
        migrations.CreateModel(
            name='Juice_option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('fruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Option')),
                ('juice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Juice')),
            ],
        ),
        migrations.CreateModel(
            name='Juice_fruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('fruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Fruit')),
                ('juice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Juice')),
            ],
        ),
        migrations.AddField(
            model_name='juice',
            name='fruits',
            field=models.ManyToManyField(through='product.Juice_fruit', to='product.Fruit'),
        ),
        migrations.AddField(
            model_name='juice',
            name='options',
            field=models.ManyToManyField(through='product.Juice_option', to='product.Option'),
        ),
        migrations.CreateModel(
            name='Coffee_and_other_option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Option')),
                ('Coffee_and_other', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Coffee_and_other')),
            ],
        ),
        migrations.AddField(
            model_name='coffee_and_other',
            name='options',
            field=models.ManyToManyField(through='product.Coffee_and_other_option', to='product.Option'),
        ),
    ]
