# Generated by Django 3.0.5 on 2020-04-03 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruit',
            name='fruit_price',
        ),
    ]
