# Generated by Django 3.0.5 on 2020-04-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffee_and_other',
            name='coffee_type',
        ),
        migrations.AlterField(
            model_name='drink_info',
            name='drink_type',
            field=models.CharField(choices=[('Hot', 'Hot'), ('Iced', 'Iced'), ('Frappe', 'Frappe')], max_length=50),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='e_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='promo_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='s_date',
            field=models.DateField(),
        ),
    ]
