# Generated by Django 3.0.5 on 2020-04-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200415_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Order_payment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='receipt_id',
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='Reciept',
        ),
    ]
