# Generated by Django 3.0.5 on 2020-04-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200415_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='finish_flag',
            field=models.BooleanField(default=False),
        ),
    ]
