# Generated by Django 3.0.5 on 2020-04-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_order_finish_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee_and_other',
            name='sweetness',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
