# Generated by Django 3.0.5 on 2020-04-15 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_coffee_and_other_sweetness'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juice_option',
            old_name='fruit',
            new_name='option',
        ),
    ]
