# Generated by Django 3.0.5 on 2020-04-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_drink_info_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink_info',
            name='picture',
            field=models.ImageField(blank=True, default='product/default.png', null=True, upload_to='product/'),
        ),
    ]
