# Generated by Django 3.0.5 on 2020-04-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20200416_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='picture',
            field=models.ImageField(blank=True, default='Fruit/default.png', null=True, upload_to='Fruit/'),
        ),
        migrations.AddField(
            model_name='option',
            name='picture',
            field=models.ImageField(blank=True, default='Option/default.png', null=True, upload_to='Option/'),
        ),
    ]
