# Generated by Django 3.0.5 on 2020-04-18 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_promotion_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='c_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Customer'),
        ),
    ]
