# Generated by Django 3.0.5 on 2020-04-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20200418_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
