# Generated by Django 3.0.5 on 2020-04-18 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_promotion_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='promo_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Promotion'),
        ),
    ]
