# Generated by Django 3.0.5 on 2020-04-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20200418_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink_info',
            name='how_to_make',
            field=models.TextField(default=''),
        ),
    ]
