# Generated by Django 3.0.5 on 2020-04-29 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_customer_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
